{
  "NServiceBus.MessageId": "2815f689-5c39-4e9a-a823-a85d00d6c0d9",
  "NServiceBus.MessageIntent": "Reply",
  "NServiceBus.ReplyToAddress": "Samples.Mvc.Server",
  "NServiceBus.CorrelationId": "c199ac4e-b86f-4c59-8814-a85d00d68eaf",
  "NServiceBus.OriginatingMachine": "CLN10907",
  "NServiceBus.OriginatingEndpoint": "Samples.Mvc.Server",
  "$.diagnostics.originating.hostid": "455a786552e4de8d5c304a747891df30",
  "NServiceBus.ContentType": "text\/xml",
  "NServiceBus.EnclosedMessageTypes": "NBusShared.Response.GetCompaniesResponse, NBusShared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
  "NServiceBus.RelatedTo": "c199ac4e-b86f-4c59-8814-a85d00d68eaf",
  "NServiceBus.ConversationId": "ceed3e8c-2a06-4e99-9fd4-a85d00d68eaf",
  "NServiceBus.Version": "6.4.3",
  "NServiceBus.TimeSent": "2018-01-03 13:01:53:612544 Z",
  "NServiceBus.ExceptionInfo.ExceptionType": "System.InvalidOperationException",
  "NServiceBus.Retries.Timestamp": "2018-01-03 13:02:36:870163 Z",
  "NServiceBus.ExceptionInfo.HelpLink": null,
  "NServiceBus.ExceptionInfo.Message": "No handlers could be found for message type: NBusShared.Response.GetCompaniesResponse",
  "NServiceBus.ExceptionInfo.Source": "NServiceBus.Core",
  "NServiceBus.ExceptionInfo.StackTrace": "System.InvalidOperationException: No handlers could be found for message type: NBusShared.Response.GetCompaniesResponse\u000d\u000a   vid NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext() i C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Pipeline\\Incoming\\LoadHandlersConnector.cs:rad 31\u000d\u000a--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   vid NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext() i C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Pipeline\\Incoming\\DeserializeLogicalMessagesConnector.cs:rad 33\u000d\u000a--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   vid NServiceBus.ReceivePerformanceDiagnosticsBehavior.<Invoke>d__2.MoveNext() i C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Performance\\Statistics\\ReceivePerformanceDiagnosticsBehavior.cs:rad 40\u000d\u000a--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   vid NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext() i C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Performance\\Statistics\\ProcessingStatisticsBehavior.cs:rad 27\u000d\u000a--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   vid NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext() i C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Pipeline\\Incoming\\TransportReceiveToPhysicalMessageProcessingConnector.cs:rad 37\u000d\u000a--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   vid NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext() i C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Pipeline\\MainPipelineExecutor.cs:rad 32\u000d\u000a--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   vid System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\u000d\u000a   vid NServiceBus.LearningTransportMessagePump.<ProcessFile>d__9.MoveNext() i C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Transports\\Learning\\LearningTransportMessagePump.cs:rad 277",
  "NServiceBus.TimeOfFailure": "2018-01-03 13:18:25:215151 Z",
  "NServiceBus.FailedQ": "Samples.Mvc.WebApplication-1",
  "NServiceBus.ProcessingMachine": "CLN10907",
  "NServiceBus.ProcessingEndpoint": "Samples.Mvc.WebApplication",
  "$.diagnostics.hostid": "4e4036b1be04d1fc58b6a96fdac95d49",
  "$.diagnostics.hostdisplayname": "CLN10907"
}